Carga de archivos para vigesimo septimo cloud build

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -9,3 +9,17 @@ steps:
         --project=$PROJECT_ID
 
   timeout: '3600s'
+
+- name: 'gcr.io/cloud-builders/gcloud'
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+      RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" \
+                      -d "" -X POST $_APP_BASE_URL)
+      if [ "200" != "$$RESPONSE" ];
+      then
+          echo "FAIL: migrations failed" exit 1;
+      else
+          echo "PASS: migrations ran successfully"
+      fi
